[core_settings]
log_timestamp = false
log_error_details = true
log_level = "debug" # Possible values: "debug", "info", "warn", "error", "trace"
allow_root = true

[listener]
listener_type = "DomainSocket"
timeout = 200 # in milliseconds
socket_path = "/parsec/quickstart/parsec.sock"

[authenticator]
# auth_type = "UnixPeerCredentials"
auth_type = "Direct"

[[key_manager]]
name = "on-disk-manager"
manager_type = "OnDisk"
store_path = "/parsec/quickstart/mappings"

[[provider]]
provider_type = "MbedCrypto"
key_info_manager = "on-disk-manager"
