package org.parallaxsecond.parsec.client.exceptions;

/** Errors generated by interacting with the underlying IPC mechanism */
public class IpcException extends ClientException {
  public IpcException(String message) {
    super(message, null);
  }
}
