package org.parallaxsecond.parsec.protocol.requests;

import lombok.Getter;

/** Errors generated by the Parsec interface library */
public final class InterfaceException extends RuntimeException {
  @Getter private final ResponseStatus responseStatus;

  public InterfaceException(Exception e) {
    super(e.getMessage(), e);
    this.responseStatus = null;
  }

  public InterfaceException(ResponseStatus responseStatus, String message) {
    super(message, null);
    this.responseStatus = responseStatus;
  }

  public InterfaceException(ResponseStatus responseStatus, Exception e) {
    super(e.getMessage(), e);
    this.responseStatus = responseStatus;
  }
}
